### ISSUE TITLE
not able to import ctf.core in python 3.6

### ISSUE THREAD

**Issue by nickirk** [cyclops-community/ctf#108]
Hi,

I have been compiling and testing and found out that since this commit: 
0e7260bf3f55e088dadbacf86b1dd866be03b868

every time I try to 
```python
from ctf.core import *
```
I get this error
```python
ImportError: /home/xxx/.local/lib/python3.6/site-packages/ctf/core.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN7CTF_int6tensor16get_distributionEPPcRN3CTF13Idx_PartitionES5_
```
Has anyone else experienced the same?

**Comment by solomonik** [comment]
I think this would happen if at build time for the python library or at runtime, the path points to an out of date version of the C++ library. If this is a possibility, I would recommend running `make python_uninstall`, `make uninstall` (as superuser if install path in global dir), and `make clean`, then `make python` and `make python_test` to create and test a new local build (and if that works, `make install` with superuser if necessary, plus make `python_install`).

**Comment by nickirk** [comment]
Thanks! It works. I will close this issue.
