### ISSUE TITLE
In Python lib sparse and sparse tensor contraction to scalar yields 0. 

### ISSUE THREAD

**Issue by nickirk** [cyclops-community/ctf#109]
Hello,

I found that when two sparse tensors are fully contracted to a scalar it always yield 0. Minimum code
```python
import ctf
import numpy 

a = ctf.tensor([10,10,10], sp=1)
a.fill_sp_random(-1.,1)
b = ctf.tensor([10,10,10], sp=1)
b.fill_sp_random(-1.,1)

c1 = ctf.einsum("abc,abc->", a, b)
d1 = numpy.einsum("abc,abc->", a.to_nparray(), b.to_nparray())

print("c1=",c1,"d1=",d1)
```
This test is not in the test_sparse.py. 

Is this sparse  sparse to scalar not supported or it is a bug?

**Comment by solomonik** [comment]
Thanks for reporting this, commit e5bf8e8 should fix this bug in the python interface.
