### ISSUE TITLE
Unreasonable memory usage in reshape

### ISSUE THREAD

**Issue by yangcal** [cyclops-community/ctf#112]
Hi Edgar,

I've noticed unreasonable memory error when doing ctf reshape in some setups. In my case I'm reshaping a size 150994944 vector to (64,64,64,2,2,12,12) tensor. It went correctly when I'm using ppn32 but crashed with out-of-memory error when  using ppn56. Note in both cases I have very sufficient memory(8 nodes with 300gb each). The profiling output and error file can be found in https://github.com/yangcal/debug_files

Thanks,
Yang

**Comment by solomonik** [comment]
@yangcal based on the debug output I pushed a possible fix to branch fix_vec_redist, would you please try that out? If it does not fix, will try to reproduce on Stampede2.

**Comment by yangcal** [comment]
Hi Edgar,

The fixes in fix_vec_redist appear to have made the matter worse. 

Master: ppn32_n1 and ppn32_n8 works, ppn56_n1 and ppn56_n8 failed
fix_vec_redist: all the above failed.

debug output can be found here: [https://github.com/yangcal/debug_files/tree/main/fix_vec_redist](url). Files with "fvr" are for the fix_vec_redist branch and a simple python script is also attached.

**Comment by solomonik** [comment]
@yangcal I see, I think I found the real problem and pushed a commit to master (51069cb) to address this. Please let me know if it fixes the problem on your end, was able to reproduce what I believe is the problem on my machine in a different configuration.

**Comment by yangcal** [comment]
I can confirm the recent commit fixes all the problem, thanks!
