### ISSUE TITLE
fat QR - lower triangular part of R not set to zero

### ISSUE THREAD

**Issue by jcmgray** [cyclops-community/ctf#113]
``ctf`` currently happily takes the QR of a fat matrix, ``X``, (shape ``(m, n)`` with ``m < n``), but the lower 'triangular' part of the rectangular matrix ``R`` is not set to zero meaning, ``Q @ R != X``.

```python
import ctf
m, n = 4, 7
X = ctf.random.random((m, n))
Q, R = ctf.qr(X)
(Q @ R - X).sum()
# -0.06291466098395088
```
the following workaround sets the values manually to zero using numpy:
```python
import numpy as np

iis, jjs = np.indices(R.shape)
inds = np.argwhere(iis > jjs)
vals = np.tile(0.0, len(inds))
R.write(inds, vals)

(Q @ R - X).sum()
# 1.987993103469421e-15
```
showing the decomposition is otherwise correct.

**Comment by solomonik** [comment]
@jcmgray thanks for pointing this out, should be fixed by commit 6bc9d7c
