### ISSUE TITLE
[question] setting all nonzeros to a value

### ISSUE THREAD

**Issue by rohany** [cyclops-community/ctf#142]
Is it possible to read a tensor from disk and then set all nonzero entries of that tensor to a particular value? I don't see anything like this in the API, so double checking here.

**Comment by raghavendrak** [comment]
You can use `Transform`
`// add 1 to all nonzeros in v`
`Transform<float>([](float & a){ a+=1; })(v["i"]);`
Look at codes in `./examples`

**Comment by rohany** [comment]
Thanks, this worked!
