### ISSUE TITLE
Values of tensors not getting printed into a file

### ISSUE THREAD

**Issue by alejandrogallo** [cyclops-community/ctf#45]
I've come accross a small but annoying issue.
When I print a tensor into a file like

```c++
FILE *fp;
fp = open("myfile.ctf");
myTensor.print(fp);
```
I get everything but the values of the tensor, i.e.
```
[0][0](0, <>)
[1][0](1, <>)
[2][0](2, <>)
[3][0](3, <>)
[4][0](4, <>)
[5][0](5, <>)
[6][0](6, <>)
[7][0](7, <>)
[8][0](8, <>)
```
for instance.
I went to the source code and I think it is because in the implemenation of the `print` method in
`src/tensor/untyped_tensor.cxx` in line 1799 one does not pass the `fp` argument into the
`print` mehtod of the algebraic structure `sr`.

**Comment by solomonik** [comment]
Thanks for pointing out the issue and fix.

**Comment by alejandrogallo** [comment]
Gladly!
