### ISSUE TITLE
Problems with automated build on OSX

### ISSUE THREAD

**Issue by solomonik** [cyclops-community/ctf#49]
- [x]  apple clang does not support -Bdynamic/-Bstatic (manually fixed by removal of all -Wl,-Bdynamic and -Wl,-Bstatic from configure file)
- [ ]  latest openmpi does not seem to provide MPI::COMPLEX_DOUBLE (manually fixed by replacing with MPI_CXX_COMPLEX_DOUBLE)
- [x]  C++11 not supported with usual flag for python build, (manually fixed by adding to extra_compile_args -stdlib=libc++ -mmacosx-version-min=10.7 as suggested in https://github.com/automl/auto-sklearn/issues/304)

should automate all of these when apple/clang is detected.

**Comment by jeffhammond** [comment]
MPI-3.0 consummated deprecation of C++ bindings in MPI-2.2 by deleting them.  While no implementation has made a concerted effort to remove support for them, the prudent thing to do is remove all instances of `MPI::` from your code in favor of `MPI_`, i.e. convert from C++ bindings to C bindings.
