### ISSUE TITLE
unable to scale expressions by std::complex<double>

### ISSUE THREAD

**Issue by kostrzewa** [cyclops-community/ctf#52]
In a contraction expression involving tensors of std::complex<double>, it is not possible to scale the expression by a complex number. Scaling by a real number works fine, however.

**Comment by solomonik** [comment]
This is possible in C++ by calling `Tensor<...>::contract()`. I think issues parsing the expressions were encountered when trying to handle complex scalars automatically in Einstein summation expressions.

For Python, indeed we are lacking a way of doing this nicely (will try to fix this week, likely just by interfacing explicitly to contract() and sum(), handling them in Einstein summation expressions might again end up problematic).

As a work around for now, you can just cast the scalar to a tensor, e.g.

```w.i("i") << ctf.astensor(2+3j,dtype=np.complex64).i("")*v.i("i")```

Sorry for the slow response on this.
