### ISSUE TITLE
Matrix Market I/O in CTF

### ISSUE THREAD

**Issue by BenBrock** [cyclops-community/ctf#59]
I'm not totally sure if this is the correct venue for CTF usage questions---if not, please redirect me.

What's the most straightforward way to load Matrix Market format sparse matrices into CTF?  I'm using the C++ API, but could switch to Python.

I don't see a Matrix Market reader in the source.  Do I need to use my own parallel reader to read in chunks to a CSR on each process and then initialize a Tensor with them?  Which constructor should I use?

**Comment by solomonik** [comment]
Hi Ben,

We are actually currently working on an I/O reader for sparse tensors and matrices (some initial work is on a fork https://github.com/jasonzhang929/ctf and I am hoping we can finish it up and merge it, likely into a branch of the main repo, within this week).

For coordinate format, you can read a subset of entries using MPI-I/O on each processor and enter them into a created CTF Matrix via any variant of the write() routine (http://solomon2.web.engr.illinois.edu/ctf/classCTF_1_1Tensor.html#a3a4829cd86316e11b7ba1f3e15ea6f58).

We've previously done something similar for reading graphs via MPI-I/O into CTF tensors, I believe the format is quite close to the COO format the matrix market uses. The code for that is in our graph_centrality repo, although its not production quality (we are currently cleaning it up and generalizing).

https://github.com/solomonik/graph_centrality/blob/master/graph_io.cxx
https://github.com/solomonik/graph_centrality/blob/master/test_btwn_central.cxx#L66

Line 102 of the last file uses the aforementioned write() interface.

I'll keep this open for now and update once we have the general sparse I/O reader done and intgrated into CTF.

For the dense format, we have an existing routine for general tensors http://solomon2.web.engr.illinois.edu/ctf/classCTF__int_1_1tensor.html#a8c65d839629f304391c437e8decc76bb

but it assumes one tensor entry per line, which is slightly different from the matrix market format (although I guess a brief search and replace might address the differences).

**Comment by solomonik** [comment]
This is now merged into master and should be working on python level, see examples/checkpoint_sparse.cxx
