### ISSUE TITLE
Transform crash under MPI

### ISSUE THREAD

**Issue by ryanlevy** [cyclops-community/ctf#65]
I had trouble with the following snippet while trying to do element wise multiplication:
```c++
    vector<int> inds = {1,1};
    CTF::Tensor<> A(2,inds.data());
    A["ij"] = 1.;
    A.print();
    CTF::Tensor<> S(1,inds.data());
    S["i"] = 2.;
    S.print();
    CTF::Transform<double,double>([](double s, double& a){ a*=s; })(S["j"],A["ij"]); //!!
    A.print();
```
This runs fine with one MPI thread but with 2+ segfaults. Swapping `S["j"]` -> `S["i"]` works but the tensor isn't always in that format. 

The easy workaround for this (I assume) is to instead replace that line with `A["ij"]=S["i"]*A["ij"];`

**Comment by solomonik** [comment]
@ryanlevy I am unable to reproduce the segfault with the latest version of CTF. I am able to run the following code with 2 MPI processes without error.
```
#include <ctf.hpp>
#include <vector>
#include <mpi.h>

int main(int argc, char **argv){
    MPI_Init(&argc,&argv);
    CTF::World w();
    vector<int> inds = {1,1};
    CTF::Tensor<> A(2,inds.data());
    A["ij"] = 1.;
    A.print();
    CTF::Tensor<> S(1,inds.data());
    S["i"] = 2.;
    S.print();
    CTF::Transform<double,double>([](double s, double& a){ a*=s; })(S["j"],A["ij"]); //!!
    A.print();
    MPI_Finalize();
    return 0;
}
```
Same behavior when swapping `S["j"]->S["i"]`. Let me know if something should be tweaked or if using the latest version of CTF addresses the error (off the top of my head I don't recall any changes in the last 1-2 weeks that would have addressed such a bug, although I think there was some scalar handling stuff that changed in last 1-2 months).

**Comment by ryanlevy** [comment]
That does appear to be the case, I'm not sure what happened! I'll just close this one out then. Thanks for looking into it
