### ISSUE TITLE
Scalars destroy sparse tensors

### ISSUE THREAD

**Issue by ryanlevy** [cyclops-community/ctf#69]
When multiplying by a CTF scalar, a sparse tensor seems to be set to zero
Minimal reproducing code:
```c++
vector<int> inds = {1,2,2};
CTF::Tensor<> A(3,inds.data());
A.fill_random(0,1);
A.print();
A.sparsify();
auto invC = 1.;
CTF::Scalar<double> cs(invC);
A["ijk"]*=cs[""]; // A["ijk"]*=1.; works
A.print();
```

Output:
```
Printing tensor ETXS03
printing mapping of dense tensor ETXS03
CTF: ETXS03 mapped to order 2 topology with dims: 2  2
[0][0][0](0, <1.59793E-01>)
[0][1][0](1, <1.33877E-01>)
[0][0][1](2, <9.03604E-01>)
[0][1][1](3, <5.58766E-01>)
Printing tensor ETXS03
printing mapping of sparse tensor ETXS03
CTF: ETXS03 mapped to order 2 topology with dims: 2  2
```

**Comment by solomonik** [comment]
@ryanlevy this issue seems to have to do with sparse tensor input and output involved in the same contraction, with pre-existing nonzeros. Above commit should address. I believe your test should now work. Please let us know if you see any further issues and thanks for reporting this.

**Comment by ryanlevy** [comment]
Looks like it's working for me now! Thanks!
