### ISSUE TITLE
Make python failed on MacOSX. ld: library not found for -lstdc++

### ISSUE THREAD

**Issue by AdrianTanTeckKeng** [cyclops-community/ctf#70]
I am using anaconda with python version 3.7.1, Cython 0.29.2, clang 1001.0.46.4 . Make python fails with the following output error:

mpicxx -bundle -undefined dynamic_lookup -L/Users/atanteck/anaconda3/lib -arch x86_64 -L/Users/atanteck/anaconda3/lib -arch x86_64 -L/Users/atanteck/Desktop/cyclops/ctf/lib_shared -arch x86_64 /Users/atanteck/Desktop/cyclops/ctf/lib_python/ctf/core.o -lctf -lblas -llapack -o /Users/atanteck/Desktop/cyclops/ctf/lib_python/ctf/core.cpython-37m-darwin.so -L/Users/atanteck/Desktop/cyclops/ctf/lib_shared -O3 -std=c++0x -DOMP_OFF
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'mpicxx' failed with exit status 1

The setup.py config files is as follows:
rom distutils.core import setup
from distutils.extension import Extension
import numpy

import os
os.environ["CXX"] = "mpicxx"
os.environ["CC"] = "mpicxx"

from Cython.Distutils import build_ext
from Cython.Build import cythonize

mod_core = ["ctf.core", "ctf/core.pyx"]
mod_rand = ["ctf.random", "ctf/random.pyx"]
mods = [mod_core, mod_rand]
ext_mods = []
for mod in mods:
    ext_mods.append(Extension(
            mod[0],
            [mod[1]],
            language="c++",
            include_dirs=[numpy.get_include(),"/Users/atanteck/Desktop/cyclops/ctf/include","."],
            libraries="-lctf   -lblas  -llapack".replace('-l','').replace('','').split(),
            extra_compile_args="-O3 -std=c++0x -DOMP_OFF -stdlib=libc++ -mmacosx-version-min=10.7".split(),
            extra_link_args="-L/Users/atanteck/Desktop/cyclops/ctf/lib_shared -O3 -std=c++0x -DOMP_OFF   ".split()
        ))

setup(name="CTF",packages=["ctf"],version="1.5.4",cmdclass = {'build_ext': build_ext},ext_modules = cythonize(ext_mods))

The setup.py file includes -stdlib=libc++ instead of libstdc++, so I am unsure what to make of the error. Any help is appreciated.

**Comment by solomonik** [comment]
@AdrianTanTeckKeng I think this is the same as #66 and would be addressed by setting an environment variable like

`export MACOSX_DEPLOYMENT_TARGET=10.8`

(or perhaps 10.9). Added this bit to the wiki as well.

**Comment by AdrianTanTeckKeng** [comment]
Thanks for the help, got it to work with MACOSX_DEPLOYMENT_TARGET=10.14. All the make tests for python pass too.
